Feat: work schema api
FrontMen/fm-hours pull request #167
Opened 2021-07-14 07:30 UTC by italoteix

# Changes

## Related issues

Resolves #42 

## Added

- Work-scheme types
- Helper function to mark day as holiday based on work-scheme

## Removed

- Functions that automatically creates projects based on work-scheme results

## Changed

- No longer mocked work-scheme
- App also checks work-scheme to see if is holiday

## How to test

- Check if the holidays are correctly displayed

## Screenshots

N/A

2021-07-14 09:02 UTC, lassecapel reviewed
What happens if a holiday is requested after an hour entry is already added? Is it removed from the timesheet then?

2021-07-14 09:26 UTC, italoteix commented
> What happens if a holiday is requested after an hour entry is already added? Is it removed from the timesheet then?

Good question. It isn't.
Currently, we have non-blocking logic for holidays. 
So the employee still can add hours for holidays, although he'll get a warning before submit and the admin will review the timesheet.
So if the employee holiday request is before the review, the admin can either deny the timesheet or edit it himself.

2021-07-16 13:53 UTC, mmehmetAliIzci requested changes

2021-07-16 13:53 UTC, mmehmetAliIzci commented on services/work-scheme-service.ts
> +  async getWorkScheme(params: {
Can we type the return type as `Promise<WorkScheme[] | undefined>`

2021-07-16 13:53 UTC, mmehmetAliIzci commented on store/records/actions.ts
> +    const holidays = rootState.holidays.holidays;
inline ? 🤷

2021-07-16 13:53 UTC, mmehmetAliIzci commented on store/timesheets/getters.ts
> +  getEmployeePendingWeeks(state) {
I cannot seem to find where does these getters has been used ? There seems to be no function call or not even name match on search

2021-07-20 06:29 UTC, italoteix commented on store/timesheets/getters.ts
> +  getEmployeePendingWeeks(state) {
Probably a leftover. I'll delete this entire file

2021-07-21 09:43 UTC, mmehmetAliIzci approved these changes

2021-07-21 11:32 UTC, merged