Feature/standby hours
FrontMen/fm-hours pull request #188
Opened 2021-07-22 14:17 UTC by vladPinteaFrontmen

# Changes
Employee can have standby hours toggled on and off
Timesheet now features standby hours if feature is turned on
Timesheets admin view shows stand by hours for all employees, with a label if it is no longer available. Travel expenses also always on (given that toggling it off would hide the history from when it was available). 
Employee cannot see the history of that when it isn't enabled anymore. 

additionally firestore collections moved to an enum

## Related issues
https://github.com/FrontMen/fm-hours/issues/171

## Added

New firestore collection for standby hours
Standby toggler in manage employee view
Standby hours in timesheet both on home and /timesheets

## Changed
Time records service - methods made generic to be able to perform CRUD on both time reports and standby hours

## How to test
1. Login as admin
2. Go to employees and toggle on standby hours
3. Go to home page and see a new row to fill. 
4. Fill it, save it, see it persists. You can also check firestore that it correctly updated
5. Go to /timesheets and check the sheet you filled in - see the new standby area
6. Go to another employee's timesheets, who doesn't have stand by enabled, see a label warning you it isn't available
7. Do the same for an employee without travel enabled

## Screenshots
![image](https://user-images.githubusercontent.com/85111889/126654322-8cc8dded-81ca-42fd-8bba-da1ec5e5a246.png)
![image](https://user-images.githubusercontent.com/85111889/126654378-a5ed1349-e4e1-477c-82e4-0c2183ad9d8e.png)
![image](https://user-images.githubusercontent.com/85111889/126654439-aae0ee92-b338-4151-9fdb-588792ec0654.png)

2021-07-23 07:29 UTC, lassecapel commented
can we use a badge instead of the text "not active for employee" and maybe make the whole table grey instead of primary color

2021-07-26 06:50 UTC, italoteix commented on store/records/actions.ts
> +    }, "standby_records");
Can we use the ENUM here?

2021-07-26 07:20 UTC, italoteix requested changes
While testing I couldn't create new timesheets (the project modal didn't show up).
Also, for some employees, the Standby table is still editable even if the standby hours aren't enable for him

2021-07-26 10:23 UTC, vladPinteaFrontmen commented
@italoteix updated: removed the total from standby; adding a project reenabled; 
admins should still be able to edit values even for fields that are no longer enabled.

2021-07-26 13:06 UTC, italoteix commented
Tested again. It seems that the employees that don't have the `standBy` field at the database (the ones that weren't updated using this branch) are showing up the Stand-by table as it was true. How to reproduce it: 
- Delete the `standBy` field of a user directly on the database or go to the timesheets of some user that doesn't have it (like Dean).
- Check that the stand by fields are enabled to him (should default to not)

2021-07-26 13:12 UTC, italoteix commented
If for some reason the employee logs hours only on stand-by fields, the app will show the "empty timesheet" state after saving. How to reproduce it: 
- Go to an empty week for of a employee that has the standBy enabled
- Add a new timesheet
- Log hours only in the `Stand-by hours` table
- Save it

2021-07-27 13:10 UTC, italoteix approved these changes

2021-07-27 13:51 UTC, merged