fix: send timesheet denial message via email
FrontMen/fm-hours pull request #238
Opened 2021-08-09 13:13 UTC by BrunoAl

# Changes

## Changed

Fix denial the denial button on timesheets.

## How to test

Create a new request, and try to deny it.

2021-08-09 14:42 UTC, vladPinteaFrontmen requested changes
you are emitting an event that isn't definied in "emits" at defineComponents stage
+
nothing is listening for the event in parent. 

Emitting the event shouldn't be necesary, as the modal should handle setting the denied status

Additionally when running this branch it isn't doing anything for me locally. I deny a sheet, it stays in the current state

2021-08-10 10:58 UTC, DeanMW approved these changes

2021-08-17 07:54 UTC, sanderdejong88 approved these changes

2021-08-18 08:51 UTC, DeanMW approved these changes

2021-08-19 07:49 UTC, merged