Refactor/remove logic from create monthly report data
FrontMen/fm-hours pull request #831
Opened 2023-01-03 16:17 UTC by rafaelmils

# Changes
Moving some logic from a mutation to an action and possible some this logic to related helpers

## Related issues

## Added

## Removed

## Changed

## How to test

## Screenshots

2023-01-05 09:44 UTC, marioesuc requested changes

2023-01-05 09:44 UTC, marioesuc commented on store/reports/actions.ts
> +    const activeEmployees: Employee[] = employees.filter(employee =>
Why did you need to add the type? Isn't it automatically inferred?

2023-01-05 09:44 UTC, marioesuc commented on store/reports/mutations.ts
> -  createMonthlyReportData(
You rock!!!

2023-01-05 09:44 UTC, marioesuc commented on store/reports/mutations.ts
>      state.reportData = {
Since the payload is already a MonthlyReportData type, why don't you just assign the whole payload to state.reportData? And if you do so, make sure you're creating a deep copy of the payload to avoid mutations

2023-01-05 09:44 UTC, marioesuc commented on types/reports.d.ts
> +interface MonthlyReportPreData {
Maybe calling it `MontlyReportPayload` instead to make more explicit what it's intended for?

2023-01-05 09:52 UTC, rafaelmils commented on types/reports.d.ts
> +interface MonthlyReportPreData {
hahahah, this is the name that I had before...since it makes more sense to you as well, I will change it again :P

2023-01-05 09:53 UTC, rafaelmils commented on store/reports/mutations.ts
> -  createMonthlyReportData(
hahahaha :)

2023-01-06 10:31 UTC, rafaelmils commented on store/reports/actions.ts
> +    const activeEmployees: Employee[] = employees.filter(employee =>
Correct, it's not needed here!

2023-01-06 10:35 UTC, rafaelmils commented on store/reports/mutations.ts
>      state.reportData = {
Valid one, making it simpler!

2024-03-26 07:49 UTC, closed without merging